[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
# We are intentionally leaving out 'cacheDirectories' here to reset the build
cmds = ["npm run build"]

[start]
cmd = "npm run start"
