[phases.setup]
nixPkgs = ["nodejs_20", "npm"]

[phases.install]
cmds = ["npm install --include=dev"]

[phases.build]
# We remove the problematic cache mount by overriding the build phase
cmds = ["npm run build"]
cacheDirectories = ["node_modules/.cache", ".next/cache"]

[start]
cmd = "npm run start"