services:
  postgres:
    image: postgres:15-alpine
    container_name: sankalpam_db
    environment:
      POSTGRES_USER: sankalpam_user
      POSTGRES_PASSWORD: sankalpam_password
      POSTGRES_DB: sankalpam_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sankalpam_user"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: sankalpam_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:

